paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
       - Products
      responses:
        "200":
          description: Los productos fueron devuelvos satisfactoriamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del server. Query defectuosa o un fallo a la conexion a la DB
  /api/products/{uid}:
    get:
      summary: Obtiene un product
      tags:
        - Products
      parameters:
      - name: uid
        in: path
        required: true
        description: ID del product que se solicita
        schema:
          $type: String
      responses:
        "200":
          description: Product Encontrado
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
    put:
      summary: actualiza un procuto a partir del ID
      tags:
        - Products
      parameters:
      - name: uid
        in: path
        required: true
        description: ID del producto que se solicita
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProcut'
    delete:
      summary: borra un procuto a partir del ID
      tags:
        - Products 
      parameters:
      - name: uid
        in: path
        required: true
        description: ID del producto que se solicita  
      schema:
          $type: String
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProcut'          
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID auto generado en mongo
        title:
          type: String
          description: Nombre del Producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Stock del Producto
        category:
          type: String
          description: Catergoria del producto
        photo: 
          type: String
          description: Url de la imagen del producto   
      example:
        _id: ObjectId("63e507e201199ff09788ffb2")
        title: "Mens Casual Premium Slim Fit T-Shirts"
        description: "Slim-fitting style, contrast raglan long sleeve, three-button henley p…"
        price: 12000
        stock: 21
        category: "men's clothing"
        photo: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg"
  requestBodies:
    updateProcut:
      type: object
      properties:
        title:
          type: String
          description: Nombre del Producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Stock del Producto
        category:
          type: String
          description: Catergoria del producto
        photo: 
          type: String
          description: Url de la imagen del producto  
tags: []